# Generated by Django 4.2.1 on 2023-05-03 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TgUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Телеграм',
                'verbose_name_plural': 'Телеграм',
            },
        ),
        migrations.AlterModelOptions(
            name='usermodel',
            options={'verbose_name': 'Администрация', 'verbose_name_plural': 'Администрация'},
        ),
    ]
