# Generated by Django 4.2.1 on 2023-05-03 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_tgusermodel_alter_usermodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tgusermodel',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='tgusermodel',
            name='is_ban_user',
            field=models.BooleanField(default=False, verbose_name='Заблокирован'),
        ),
        migrations.AddField(
            model_name='tgusermodel',
            name='is_blocked_bot',
            field=models.BooleanField(default=False, verbose_name='Заблокировал бота'),
        ),
        migrations.AddField(
            model_name='tgusermodel',
            name='is_bot',
            field=models.BooleanField(blank=True, max_length=255, null=True, verbose_name='Это бот'),
        ),
        migrations.AddField(
            model_name='tgusermodel',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Статус админа'),
        ),
        migrations.AddField(
            model_name='tgusermodel',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='tgusermodel',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='tgusermodel',
            name='tg_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True, verbose_name='ID телеграм'),
        ),
        migrations.AddField(
            model_name='tgusermodel',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ник'),
        ),
    ]
