# Generated by Django 4.2.1 on 2023-05-03 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_tgusermodel_first_name_tgusermodel_is_ban_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tgusermodel',
            name='is_bot',
        ),
    ]
