# Generated by Django 4.2.1 on 2023-05-23 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_tgusermodel_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='tgusermodel',
            name='last_login',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Последняя сессия'),
        ),
    ]
