# Generated by Django 4.1.4 on 2023-06-06 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_tgusermodel_tg_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='notice',
            field=models.BooleanField(default=False, help_text='Получение уведомлений о создании товаров поставщиками', verbose_name='Отправлять уведомления'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='report',
            field=models.BooleanField(default=False, help_text='Получение отчетов в конце дня.', verbose_name='Отправлять отчеты'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='tg_id',
            field=models.CharField(default=0, max_length=255, verbose_name='ID Телеграм'),
        ),
    ]
