# Generated by Django 4.1.4 on 2023-06-07 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0002_rename_countrymodel_citymodel'),
        ('user', '0013_usermodel_notice_usermodel_report_usermodel_tg_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tgusermodel',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='geography.citymodel', verbose_name='Город'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='notice',
            field=models.BooleanField(default=False, help_text='Получение уведомлений о создании товаров поставщиками', verbose_name='Уведомления'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='report',
            field=models.BooleanField(default=False, help_text='Получение отчетов в конце дня.', verbose_name='Отчеты'),
        ),
    ]
