# Generated by Django 4.1.4 on 2023-06-07 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_tgusermodel_city_alter_usermodel_notice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tgusermodel',
            name='notice',
            field=models.BooleanField(default=True, verbose_name='Уведомления'),
        ),
    ]
