# Generated by Django 4.2.2 on 2023-07-03 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0008_segmentationmodel_segmentbasemodel_and_more'),
        ('user', '0017_alter_tgusermodel_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='tgusermodel',
            name='segment',
            field=models.ManyToManyField(blank=True, to='mailing.segmentationmodel', verbose_name='Сегменты'),
        ),
    ]
