# Generated by Django 4.2.2 on 2023-06-22 23:48

import apps.site.site_product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_product', '0002_shopsubcategorymodel_category_shopproductmodel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopkeymodel',
            options={'verbose_name': 'Параметр', 'verbose_name_plural': 'Параметры'},
        ),
        migrations.AddField(
            model_name='shopproductmodel',
            name='preview',
            field=models.ImageField(default=1, upload_to=apps.site.site_product.models.path_product, verbose_name='Превью'),
            preserve_default=False,
        ),
    ]
