# Generated by Django 4.2.2 on 2023-06-22 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_product', '0004_productcolormodel_productmemorymodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopproductmodel',
            name='p_color',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='site_product.productcolormodel', verbose_name='Цвет'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopproductmodel',
            name='p_memory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='site_product.productmemorymodel', verbose_name='Память'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shopproductmodel',
            name='p_size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='site_product.productsizemodel', verbose_name='Подкатегория'),
            preserve_default=False,
        ),
    ]
