# Generated by Django 4.2.2 on 2023-06-23 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_product', '0005_shopproductmodel_p_color_shopproductmodel_p_memory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopFilterParameterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now=True, verbose_name='Дата создания')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_product.shopcategorymodel', verbose_name='Подкатегория')),
            ],
            options={
                'verbose_name': 'Параметр',
                'verbose_name_plural': 'Параметры',
            },
        ),
        migrations.AddField(
            model_name='shoptypemodel',
            name='slug',
            field=models.SlugField(default='Phone', verbose_name='Префикс URL'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ShopKeyModel',
        ),
    ]
