# Generated by Django 4.2.2 on 2023-06-23 02:27

import apps.site.site_product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_product', '0006_shopfilterparametermodel_shoptypemodel_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoptypemodel',
            name='image',
            field=models.ImageField(default=1, upload_to=apps.site.site_product.models.path_type_product, verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
