# Generated by Django 4.2.1 on 2023-05-03 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_tgusermodel_is_bot'),
        ('geography', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CountryModel',
            new_name='CityModel',
        ),
    ]
