# Generated by Django 4.1.4 on 2023-06-10 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0002_rename_countrymodel_citymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citymodel',
            name='date_created',
            field=models.DateField(auto_now=True, verbose_name='Дата создания'),
        ),
    ]
