# Generated by Django 4.2.2 on 2023-07-03 17:35

import apps.apps.configs.geography.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0004_invitemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitemodel',
            name='image',
            field=models.ImageField(default=1, upload_to=apps.apps.configs.geography.models.path_invited, verbose_name='Картинка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invitemodel',
            name='text',
            field=models.TextField(default='asd', verbose_name='Текст'),
            preserve_default=False,
        ),
    ]
