# Generated by Django 4.2.2 on 2023-07-09 23:53

import apps.apps.configs.geography.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0005_invitemodel_image_invitemodel_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsCSVModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.apps.configs.geography.models.file_bonus, verbose_name='Файл')),
                ('date_created', models.DateField(auto_now=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Баллы',
                'verbose_name_plural': ('Баллы',),
            },
        ),
        migrations.CreateModel(
            name='PointsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('value', models.CharField(max_length=100, verbose_name='Кол-во')),
            ],
            options={
                'verbose_name': 'Баллы',
                'verbose_name_plural': ('Баллы',),
            },
        ),
    ]
