# Generated by Django 4.2.2 on 2023-07-10 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0006_pointscsvmodel_pointsmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pointscsvmodel',
            options={'verbose_name': 'Баллы', 'verbose_name_plural': 'Баллы'},
        ),
        migrations.AlterModelOptions(
            name='pointsmodel',
            options={'verbose_name': 'Значения баллов', 'verbose_name_plural': 'Значения баллов'},
        ),
        migrations.AddField(
            model_name='pointsmodel',
            name='buy',
            field=models.CharField(default=1, max_length=100, verbose_name='Сумма покупок'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pointsmodel',
            name='buy_frozen',
            field=models.CharField(default=1, max_length=100, verbose_name='Отложено'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pointsmodel',
            name='value',
            field=models.CharField(max_length=100, verbose_name='Бонусы'),
        ),
    ]
