# Generated by Django 4.2.2 on 2023-07-10 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0007_alter_pointscsvmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointsmodel',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ФИО'),
        ),
    ]
