# Generated by Django 4.2.2 on 2023-07-14 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0008_pointsmodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitemodel',
            name='name',
            field=models.CharField(help_text='Имя указывать на английском!<br><br>Ссылка: https://t.me/TuneBot_bot?start=ИМЯ_РЕФЕРАЛА', max_length=100, verbose_name='Имя реферала'),
        ),
    ]
