# Generated by Django 4.2.2 on 2023-11-27 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0011_suppprovidermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppprovidermodel',
            name='SITE_ID',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID на сайте'),
        ),
    ]
