# Generated by Django 4.1.4 on 2023-05-23 19:32

import apps.apps.mailing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailingAllModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=255, verbose_name='Тема сообщения')),
                ('image_1', models.ImageField(blank=True, null=True, upload_to=apps.apps.mailing.models.path_mailing, verbose_name='Изображение 1')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to=apps.apps.mailing.models.path_mailing, verbose_name='Изображение 2')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to=apps.apps.mailing.models.path_mailing, verbose_name='Изображение 3')),
                ('text', models.TextField(help_text='Поддерживается базовая HTML разметка<br><br>Максимум 1024 символа', max_length=1024, verbose_name='Текст')),
                ('count_success', models.IntegerField(default=0, verbose_name='Доставлено')),
                ('count_fail', models.IntegerField(default=0, verbose_name='Ошибки')),
                ('count_all', models.IntegerField(default=0, verbose_name='Всего')),
                ('status', models.CharField(choices=[('0', 'Не отправлено'), ('1', 'В процессе'), ('2', 'Завершено'), ('3', 'Прервано'), ('4', 'Внутренняя ошибка')], default='0', max_length=255, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Рассылка всем',
                'verbose_name_plural': 'Рассылка всем',
            },
        ),
    ]
