# Generated by Django 4.1.4 on 2023-05-23 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailingallmodel',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='mailingallmodel',
            name='date_updated',
        ),
        migrations.AddField(
            model_name='mailingallmodel',
            name='date_send',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки'),
        ),
        migrations.AlterField(
            model_name='mailingallmodel',
            name='text',
            field=models.TextField(blank=True, help_text='Поддерживается базовая HTML разметка<br><br>Максимум 1024 символа', max_length=1024, null=True, verbose_name='Текст'),
        ),
    ]
