# Generated by Django 4.1.4 on 2023-05-23 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_remove_mailingallmodel_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingallmodel',
            name='redis_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Идентификатор'),
        ),
    ]
