# Generated by Django 4.1.4 on 2023-05-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_mailingallmodel_redis_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingallmodel',
            name='status',
            field=models.CharField(choices=[('0', 'Не отправлено'), ('1', 'Процесс'), ('2', 'Завершено'), ('3', 'Прервано'), ('4', 'Внутренняя ошибка')], default='0', max_length=255, verbose_name='Статус'),
        ),
    ]
