# Generated by Django 4.2.2 on 2023-07-03 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0003_alter_citymodel_date_created'),
        ('mailing', '0005_mailingcitymodel_remove_mailingallmodel_image_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingcitymodel',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='geography.citymodel', verbose_name='Город'),
            preserve_default=False,
        ),
    ]
