# Generated by Django 4.2.2 on 2023-07-03 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_productmodel_date_sale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mailing', '0007_mailingallmodel_products_mailingcitymodel_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='SegmentationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now=True, verbose_name='Дата создания')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Сегменты аудитории',
                'verbose_name_plural': 'Сегменты аудитории',
            },
        ),
        migrations.CreateModel(
            name='SegmentBaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now=True, verbose_name='Дата создания')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('text', models.TextField(verbose_name='Текст')),
                ('status', models.CharField(choices=[('0', 'Не отправлено'), ('1', 'Процесс'), ('2', 'Завершено'), ('3', 'Прервано'), ('4', 'Внутренняя ошибка')], default='0', max_length=255, verbose_name='Статус')),
                ('count_all', models.IntegerField(default=0, editable=False)),
                ('count_success', models.IntegerField(default=0, editable=False)),
                ('count_fail', models.IntegerField(default=0, editable=False)),
            ],
            options={
                'verbose_name': 'Опрос',
                'verbose_name_plural': 'Опрос',
            },
        ),
        migrations.AlterField(
            model_name='mailingallmodel',
            name='products',
            field=models.ManyToManyField(blank=True, help_text='Оставьте пустым, если не требуется.', to='product.productmodel', verbose_name='Товары'),
        ),
        migrations.AlterField(
            model_name='mailingcitymodel',
            name='products',
            field=models.ManyToManyField(blank=True, help_text='Оставьте пустым, если не требуется.', to='product.productmodel', verbose_name='Товары'),
        ),
        migrations.CreateModel(
            name='SegmentationStepModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now=True, verbose_name='Дата создания')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('step', models.SmallIntegerField(verbose_name='Номер шаг')),
                ('text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Вопрос')),
                ('name', models.CharField(max_length=255, verbose_name='Кнопка')),
                ('to', models.SmallIntegerField(blank=True, null=True, verbose_name='Направить к шагу')),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.segmentbasemodel', verbose_name='Определить')),
                ('finish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mailing.segmentationmodel', verbose_name='Определить')),
            ],
            options={
                'verbose_name': 'Шаг',
                'verbose_name_plural': 'Шаги',
            },
        ),
        migrations.CreateModel(
            name='SegmentationReadyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now=True, verbose_name='Дата создания')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.segmentbasemodel', verbose_name='Определить')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.segmentationmodel', verbose_name='Определить')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
