# Generated by Django 4.2.2 on 2023-07-03 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_tgusermodel_segment'),
        ('mailing', '0008_segmentationmodel_segmentbasemodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segmentationreadymodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tgusermodel', verbose_name='Пользователь'),
        ),
    ]
