# Generated by Django 4.2.2 on 2023-07-09 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0011_remove_mailingsegmentmodel_segment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingsegmentmodel',
            name='segment',
            field=models.ManyToManyField(to='mailing.segmentationmodel', verbose_name='Сегменты'),
        ),
    ]
