# Generated by Django 4.2.1 on 2023-05-14 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geography', '0002_rename_countrymodel_citymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CSVLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('file', models.FileField(upload_to='', verbose_name='Файл')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geography.citymodel', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Актуализация',
                'verbose_name_plural': 'Актуализация',
            },
        ),
    ]
