# Generated by Django 4.1.4 on 2023-06-09 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_userlogs_productlogs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlogs',
            name='city',
        ),
    ]
