# Generated by Django 4.1.4 on 2023-06-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_remove_userlogs_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogs',
            name='users',
            field=models.JSONField(null=True, verbose_name='Пользователи'),
        ),
    ]
