# Generated by Django 4.2.2 on 2023-06-15 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_productmodel_amount_buy_alter_productmodel_name'),
        ('logs', '0005_alter_csvlogs_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlogs',
            name='date_created',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.CreateModel(
            name='AmountProductLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(verbose_name='Дата')),
                ('amount', models.IntegerField(default=0, verbose_name='Сумма дня')),
                ('product', models.ManyToManyField(to='product.productmodel', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Продажи Б/У Товары',
                'verbose_name_plural': 'Продажи Б/У Товары',
            },
        ),
    ]
