# Generated by Django 4.2.2 on 2023-07-09 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0007_alter_productlogs_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(verbose_name='Дата')),
                ('chapter', models.CharField(max_length=255, verbose_name='Раздел')),
                ('button', models.CharField(max_length=255, verbose_name='Раздел')),
                ('count', models.IntegerField(default=1, verbose_name='Кол-во')),
            ],
            options={
                'verbose_name': 'Разделы',
                'verbose_name_plural': 'Разделы',
            },
        ),
    ]
