# Generated by Django 4.2.2 on 2023-07-09 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0008_chapterlogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapterlogs',
            name='date_created',
            field=models.DateField(db_index=True, verbose_name='Дата'),
        ),
    ]
