# Generated by Django 4.2.2 on 2023-07-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0009_alter_chapterlogs_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingProductLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(db_index=True, verbose_name='Дата')),
                ('count', models.IntegerField(default=1, verbose_name='Кол-во')),
            ],
            options={
                'verbose_name': 'Бронь',
                'verbose_name_plural': 'Бронь',
            },
        ),
        migrations.CreateModel(
            name='ManagerLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(db_index=True, verbose_name='Дата')),
                ('count', models.IntegerField(default=1, verbose_name='Кол-во')),
            ],
            options={
                'verbose_name': 'Менеджер',
                'verbose_name_plural': 'Менеджер',
            },
        ),
    ]
