# Generated by Django 4.1.4 on 2023-05-28 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_conf', '0003_remove_productstatemodel_category_productkitmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductKitModel',
        ),
    ]
