# Generated by Django 4.1.4 on 2023-05-28 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_conf', '0004_delete_productkitmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductKitModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=350, verbose_name='Описание')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_conf.productcategorymodel', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Комплект',
                'verbose_name_plural': 'Комплекты',
            },
        ),
    ]
