# Generated by Django 4.1.4 on 2023-06-10 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_conf', '0005_productkitmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategorymodel',
            name='date_created',
            field=models.DateField(auto_now=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='productmanufacturermodel',
            name='date_created',
            field=models.DateField(auto_now=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='producttypemodel',
            name='date_created',
            field=models.DateField(auto_now=True, verbose_name='Дата создания'),
        ),
    ]
