# Generated by Django 4.2.2 on 2023-07-14 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_conf', '0006_alter_productcategorymodel_date_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productkitmodel',
            options={'ordering': ('category', '-name'), 'verbose_name': 'Комплект', 'verbose_name_plural': 'Комплекты'},
        ),
        migrations.AlterModelOptions(
            name='productsubcategorymodel',
            options={'ordering': ('name',), 'verbose_name': 'Подкатегория', 'verbose_name_plural': 'Подкатегории'},
        ),
    ]
