# Generated by Django 4.1.4 on 2023-05-28 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_conf', '0005_productkitmodel'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='kit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product_conf.productkitmodel', verbose_name='Комплект'),
            preserve_default=False,
        ),
    ]
