# Generated by Django 4.1.4 on 2023-05-30 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_newproductmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newproductmodel',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Название'),
        ),
    ]
