# Generated by Django 4.1.4 on 2023-06-03 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_newproductmodel_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='newproductmodel',
            name='params',
            field=models.TextField(blank=True, null=True, verbose_name='Ключи'),
        ),
    ]
