# Generated by Django 4.1.4 on 2023-06-03 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_newproductmodel_params'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newproductmodel',
            old_name='price',
            new_name='amount',
        ),
    ]
