# Generated by Django 4.1.4 on 2023-06-03 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_rename_price_newproductmodel_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newproductmodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='newproductmodel',
            name='tilda_UID',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Tilda UID'),
        ),
    ]
