# Generated by Django 4.1.4 on 2023-06-03 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_newproductmodel_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newproductmodel',
            name='tilda_UID',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='Tilda UID'),
        ),
    ]
