# Generated by Django 4.1.4 on 2023-06-03 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_newproductmodel_tilda_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='newproductmodel',
            name='update',
            field=models.BooleanField(default=True, verbose_name='Обновлять?'),
        ),
    ]
