# Generated by Django 4.1.4 on 2023-06-04 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_remove_newproductmodel_params'),
    ]

    operations = [
        migrations.AddField(
            model_name='newproductmodel',
            name='params',
            field=models.JSONField(blank=True, null=True, verbose_name='Ключи'),
        ),
    ]
