# Generated by Django 4.1.4 on 2023-06-05 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_newproductmodel_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='is_sale',
            field=models.BooleanField(default=False, verbose_name='Добавить в раздел скидок'),
        ),
    ]
