# Generated by Django 4.1.4 on 2023-06-05 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_alter_productmodel_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='is_sale',
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='amount',
            field=models.BigIntegerField(blank=True, max_length=15, null=True, verbose_name='Цена'),
        ),
    ]
