# Generated by Django 4.1.4 on 2023-06-06 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_remove_productmodel_is_sale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='amount',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Цена'),
        ),
    ]
