# Generated by Django 4.2.2 on 2023-06-15 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_productmodel_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='amount_buy',
            field=models.BigIntegerField(default=1, help_text='Цена закупки без наценки', verbose_name='Цена закупки'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='name',
            field=models.CharField(db_index=True, help_text='Название должно содержать конечную цену<br><br>Цена не должна содержать пробелы', max_length=50, verbose_name='Название'),
        ),
    ]
