# Generated by Django 4.2.2 on 2023-06-15 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_productmodel_amount_buy_alter_productmodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='custom_guarantee',
            field=models.DateField(blank=True, null=True, verbose_name='Своя гарантия'),
        ),
    ]
