# Generated by Django 4.2.2 on 2023-06-15 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_conf', '0006_alter_productcategorymodel_date_created_and_more'),
        ('product', '0023_productmodel_custom_guarantee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='guarantee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_conf.productguaranteemodel', verbose_name='Гарантия'),
        ),
    ]
