# Generated by Django 4.2.2 on 2023-07-14 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_productmodel_date_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='name',
            field=models.CharField(db_index=True, help_text='Название должно содержать конечную цену<br><br>Цена не должна содержать пробелы', max_length=90, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='text',
            field=models.TextField(blank=True, help_text='Оставить поле пустым, если не требуется.', max_length=700, null=True, verbose_name='Комментарий'),
        ),
    ]
