# Generated by Django 4.2.2 on 2023-07-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_alter_productmodel_name_alter_productmodel_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='create',
            field=models.BooleanField(default=False, verbose_name='Создано'),
        ),
    ]
