# Generated by Django 4.2.2 on 2023-07-14 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_productmodel_create'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='create',
        ),
    ]
