# Generated by Django 4.2.2 on 2023-07-14 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_remove_productmodel_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='create',
            field=models.BooleanField(default=True, verbose_name='Создано'),
        ),
    ]
