# Generated by Django 4.2.2 on 2023-07-18 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_productmodel_create'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='code',
            field=models.CharField(default=1, max_length=30, verbose_name='Код товара'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='create',
            field=models.BooleanField(default=False, verbose_name='Создано'),
        ),
    ]
