# Generated by Django 4.2.2 on 2023-07-22 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0011_suppprovidermodel'),
        ('product', '0032_pricemodel_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewPriceSearchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now=True, verbose_name='Дата создания')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('amount', models.CharField(max_length=255, verbose_name='Цена')),
                ('markup', models.CharField(max_length=255, verbose_name='Наценка устройства')),
                ('params', models.JSONField(blank=True, null=True, verbose_name='Ключи')),
                ('city', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='geography.citymodel', verbose_name='Город')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geography.suppprovidermodel', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Цены поставщиков',
                'verbose_name_plural': 'Цены поставщиков',
            },
        ),
    ]
