# Generated by Django 4.2.2 on 2023-12-04 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0012_suppprovidermodel_site_id'),
        ('product', '0034_newproductmodel_amount_sale_alter_productmodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='newproductmodel',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geography.suppprovidermodel', verbose_name='Поставщик'),
        ),
    ]
