# Generated by Django 4.2.2 on 2023-12-21 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0012_suppprovidermodel_site_id'),
        ('product', '0035_newproductmodel_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newproductmodel',
            name='provider',
        ),
        migrations.AlterField(
            model_name='newproductmodel',
            name='tilda_UID',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Новый сайт ID'),
        ),
        migrations.AlterField(
            model_name='pricemodel',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='geography.citymodel', verbose_name='Регион прайса'),
        ),
    ]
