# Generated by Django 4.2.2 on 2023-12-21 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0036_remove_newproductmodel_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newproductmodel',
            name='tilda_id',
            field=models.CharField(max_length=255, null=True, verbose_name='ID Тильды'),
        ),
    ]
