# Generated by Django 4.2.1 on 2023-05-03 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wordmodel',
            name='file',
        ),
    ]
