# Generated by Django 4.2.1 on 2023-05-05 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0003_csvmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typekeymodel',
            name='type',
        ),
        migrations.AddField(
            model_name='typekeymodel',
            name='name',
            field=models.CharField(default=1, max_length=100, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='keymodel',
            name='key',
            field=models.CharField(max_length=100, verbose_name='Ключ'),
        ),
        migrations.AlterField(
            model_name='keymodel',
            name='value',
            field=models.CharField(max_length=100, verbose_name='Значение'),
        ),
        migrations.DeleteModel(
            name='WordModel',
        ),
    ]
