# Generated by Django 4.2.1 on 2023-05-05 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0005_categorymodel_companymodel_groupmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='keymodel',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parameter.subcategorymodel', verbose_name='Подкатегория'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameter.groupmodel', verbose_name='Группа'),
        ),
    ]
