# Generated by Django 4.2.1 on 2023-05-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0008_remove_subcategorymodel_keys_categorymodel_keys_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorymodel',
            name='keys',
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='mask',
            field=models.ManyToManyField(help_text='Пример<br>Серия Память Цвет', to='parameter.typekeymodel', verbose_name='Маска'),
        ),
    ]
