# Generated by Django 4.2.1 on 2023-05-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0009_remove_categorymodel_keys_categorymodel_mask'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategorymodel',
            name='mask_extra',
            field=models.ManyToManyField(help_text='Пример:<br>- Маска категории::<br>-- Серия Память Цвет:<br>- Особый атрибут:-- 2Sim:<br>', to='parameter.typekeymodel', verbose_name='Особый атрибут'),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='mask',
            field=models.ManyToManyField(help_text='Пример:<br>-- Серия Память Цвет', to='parameter.typekeymodel', verbose_name='Маска'),
        ),
    ]
