# Generated by Django 4.2.1 on 2023-05-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0010_subcategorymodel_mask_extra_alter_categorymodel_mask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategorymodel',
            name='mask_extra',
        ),
        migrations.AddField(
            model_name='subcategorymodel',
            name='extra_mask',
            field=models.ManyToManyField(blank=True, help_text='Пример:<br>- Маска категории::<br>-- Серия Память Цвет:<br><br>- Особый атрибут:<br>-- 2Sim:<br>', to='parameter.typekeymodel', verbose_name='Особый атрибут'),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='mask',
            field=models.ManyToManyField(help_text='Пример:<br>-- Серия Память Цвет<br><br>Примечание: Порядок не важен', to='parameter.typekeymodel', verbose_name='Маска'),
        ),
    ]
