# Generated by Django 4.2.1 on 2023-05-14 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0014_regionmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('key', models.CharField(max_length=10, verbose_name='Параметр')),
                ('value', models.CharField(max_length=10, verbose_name='Значение')),
                ('type', models.CharField(choices=[('default', 'default')], max_length=10, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Конфигурация',
                'verbose_name_plural': 'Конфигурация',
            },
        ),
    ]
