# Generated by Django 4.2.1 on 2023-05-14 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0016_alter_configmodel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configmodel',
            name='type',
            field=models.CharField(choices=[('bool', 'Bool'), ('int', 'Int'), ('str', 'String')], max_length=10, verbose_name='Тип'),
        ),
    ]
