# Generated by Django 4.1.4 on 2023-06-03 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0018_subcategorymodel_mask_bot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategorymodel',
            name='mask_bot',
        ),
        migrations.CreateModel(
            name='ProductOrderingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(default=0, verbose_name='Порядковый номер')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameter.subcategorymodel', verbose_name='Подкатегория')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types_bot', to='parameter.typekeymodel', verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Порядок ключей',
                'verbose_name_plural': 'Порядок ключей',
            },
        ),
    ]
