# Generated by Django 4.1.4 on 2023-06-03 00:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0019_remove_subcategorymodel_mask_bot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorderingmodel',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameter.subcategorymodel', validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(1)], verbose_name='Подкатегория'),
        ),
    ]
