# Generated by Django 4.1.4 on 2023-06-03 00:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0020_alter_productorderingmodel_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorderingmodel',
            name='order_id',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='Порядковый номер'),
        ),
        migrations.AlterField(
            model_name='productorderingmodel',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameter.subcategorymodel', verbose_name='Подкатегория'),
        ),
    ]
