# Generated by Django 4.1.4 on 2023-06-03 23:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0021_alter_productorderingmodel_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategorymodel',
            name='order_id',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='Порядковый номер'),
        ),
    ]
