# Generated by Django 4.1.4 on 2023-06-04 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0025_alter_keymodel_order_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productorderingmodel',
            options={'verbose_name': 'Порядок ключей111', 'verbose_name_plural': 'Порядок ключей111'},
        ),
        migrations.AlterModelOptions(
            name='subcategorymodel',
            options={'verbose_name': 'Подкатегории111 ', 'verbose_name_plural': 'Подкатегории111'},
        ),
    ]
