# Generated by Django 4.1.4 on 2023-06-04 03:30

import apps.apps.configs.parameter.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0026_alter_productorderingmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategorymodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=apps.apps.configs.parameter.models.path_subcategory, verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='subcategorymodel',
            name='text',
            field=models.TextField(blank=True, default='%TEXT_POSITION%', help_text='Вставьте %TEXT_POSITION% в месте, где будут указаны цены.', max_length=300, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='productorderingmodel',
            name='order_id',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(8)], verbose_name='Порядковый номер'),
        ),
    ]
