# Generated by Django 4.1.4 on 2023-06-04 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0027_subcategorymodel_image_subcategorymodel_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategorymodel',
            name='text',
            field=models.TextField(default='%TEXT_POSITION%', help_text='Вставьте %TEXT_POSITION% в месте, где будут указаны цены.', max_length=300, verbose_name='Описание'),
        ),
    ]
