# Generated by Django 4.1.4 on 2023-06-06 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0029_alter_productorderingmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymodel',
            name='order_id',
            field=models.IntegerField(default=0, verbose_name='Порядковый номер'),
        ),
    ]
