# Generated by Django 4.1.4 on 2023-06-10 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0030_companymodel_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='date_created',
            field=models.DateField(auto_now=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='companymodel',
            name='date_created',
            field=models.DateField(auto_now=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='configmodel',
            name='date_created',
            field=models.DateField(auto_now=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='csvmodel',
            name='date_created',
            field=models.DateField(auto_now=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='groupmodel',
            name='date_created',
            field=models.DateField(auto_now=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='keymodel',
            name='date_created',
            field=models.DateField(auto_now=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='date_created',
            field=models.DateField(auto_now=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='subcategorymodel',
            name='date_created',
            field=models.DateField(auto_now=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='typekeymodel',
            name='date_created',
            field=models.DateField(auto_now=True, verbose_name='Дата создания'),
        ),
    ]
