# Generated by Django 4.2.2 on 2023-11-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameter', '0032_subcategorymodel_amount_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategorymodel',
            name='amount_sale',
            field=models.IntegerField(default=0, verbose_name='Скидка на категорию'),
        ),
    ]
